AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda-Manager
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-Lambda-Manager
    Description: Lambda-Manager provides automatic log group subscription for lambda functions.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - logs
      - loggroup
      - cloudwatch
      - lambda
    HomePageUrl: https://coralogix.com
    SemanticVersion: 2.0.0
    SourceCodeUrl: https://github.com/coralogix/coralogix-aws-serverless
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Integration configuration
        Parameters:
          - LogsFilter
          - RegexPattern
          - NotificationEmail
          - DestinationArn
          - DestinationRole
          - DestinationType
          - ScanOldLogGroups
      - Label:
          default: Lambda configuration
        Parameters:
          - FunctionArchitecture
          - FunctionMemorySize
          - FunctionTimeout
Parameters:
  LogsFilter:
    Type: String
    Description: Log group filter
    Default: ''
  DestinationArn:
    Type: String
    Description: Coralogix Firehose stream / Lambda  ARN
  DestinationRole:
    Type: String
    Description: Coralogix Firehose stream / Lambda role ARN
  DestinationType:
    Type: String
    Description: firehose / lambda 
    Default: firehose
  ScanOldLogGroups:
    Type: String
    Description: Scan old log groups
    Default: false
  RegexPattern:
    Type: String
    Description: Loggroup name regex pattern
    Default: \/aws\/lambda\/.*
  FunctionMemorySize:
    Type: Number
    Description: Lambda function memory limit
    MinValue: 128
    MaxValue: 3008
    Default: 1024
  FunctionTimeout:
    Type: Number
    Description: Lambda function timeout limit
    MinValue: 30
    MaxValue: 900
    Default: 300
  NotificationEmail:
    Type: String
    Description: Failure notification email address
    MaxLength: 320
    Default: ''
Conditions:
  IsNotificationEnabled:
    Fn::Not:
      - Fn::Equals:
          - Ref: NotificationEmail
          - ''
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: CXLambdaUpdateConfig
                Effect: Allow
                Action:
                  - lambda:UpdateFunctionConfiguration
                Resource: !GetAtt LambdaFunction.Arn
              - Sid: SNSPublishPermission
                Effect: Allow
                Action:
                  - sns:Publish
                Resource: "arn:aws:sns:us-east-1:771039649440:manager4-LambdaFunctionEventInvokeConfigOnFailureTopic-xB2dSpg5hshT"
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Adds Coralogix firehose to Loggroups
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - arm64
      MemorySize:
        Ref: FunctionMemorySize
      Timeout:
        Ref: FunctionTimeout
      Environment:
        Variables:
          LOGS_FILTER:
            Ref: LogsFilter
          REGEX_PATTERN:
            Ref: RegexPattern
          DESTINATION_ARN: 
            Ref: DestinationArn
          DESTINATION_ROLE: 
            Ref: DestinationRole
          DESTINATION_TYPE:
            Ref: DestinationType
          SCAN_OLD_LOGGROUPS:
            Ref: ScanOldLogGroups
      Policies:
        - Statement:
            - Sid: CXLambdaUpdateConfig
              Effect: Allow
              Action:
                - lambda:UpdateFunctionConfiguration
                - lambda:GetFunctionConfiguration
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*"
            - Sid: CWSubscriptionPolicy
              Effect: Allow
              Action:
                - logs:PutSubscriptionFilter
                - logs:DescribeLogGroups
                - logs:DescribeSubscriptionFilters
              Resource:
                - "arn:aws:logs:*:*:*"
            - Sid: CXPassRole
              Effect: Allow
              Action: 
                - iam:PassRole
              Resource: 
                - !Sub "arn:aws:iam::${AWS::AccountId}:role/*"      
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SNS
      Events:
        EventBridgeRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source: 
                - "aws.logs"
              detail-type:
                - "AWS API Call via CloudTrail"
              detail:
                eventSource:
                  - "logs.amazonaws.com"
                eventName:
                  - "CreateLogGroup"
            Target:
                Id: cx-loggroup-target
  LambdaFunctionNotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsNotificationEnabled
    Properties:
      Protocol: email
      Endpoint:
        Ref: NotificationEmail
      TopicArn:
        Ref: LambdaFunction.DestinationTopic
