AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda-Manager
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-Lambda-Manager
    Description: Lambda-Manager provides automatic log group subscription for lambda functions.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - logs
      - loggroup
      - cloudwatch
      - lambda
    HomePageUrl: https://coralogix.com
    SemanticVersion: 1.0.3
    SourceCodeUrl: https://github.com/coralogix/coralogix-aws-serverless
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Integration configuration
        Parameters:
          - LogsFilter
          - RegexPattern
          - NotificationEmail
          - DestinationArn
          - DestinationRole
      - Label:
          default: Lambda configuration
        Parameters:
          - FunctionArchitecture
          - FunctionMemorySize
          - FunctionTimeout
Parameters:
  LogsFilter:
    Type: String
    Description: Log group filter
    Default: '?REPORT ?"Task timed out" ?"Process exited before completing" ?errorMessage ?"module initialization error:" ?"Unable to import module" ?"ERROR Invoke Error" ?"EPSAGON_TRACE:"'
  DestinationArn:
    Type: String
    Description: Coralogix Firehose stream / Lambda  ARN
  DestinationRole:
    Type: String
    Description: Coralogix Firehose stream / Lambda role ARN
  RegexPattern:
    Type: String
    Description: Loggroup name regex pattern
    Default: \/aws\/lambda\/.*
  FunctionArchitecture:
    Type: String
    Description: Lambda function architecture, possible options are [x86_64, arm64]
    AllowedValues:
      - x86_64
      - arm64
    Default: x86_64
  FunctionMemorySize:
    Type: Number
    Description: Lambda function memory limit
    MinValue: 128
    MaxValue: 3008
    Default: 1024
  FunctionTimeout:
    Type: Number
    Description: Lambda function timeout limit
    MinValue: 30
    MaxValue: 900
    Default: 300
  NotificationEmail:
    Type: String
    Description: Failure notification email address
    MaxLength: 320
    Default: ''
Conditions:
  IsNotificationEnabled:
    Fn::Not:
      - Fn::Equals:
          - Ref: NotificationEmail
          - ''
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Adds Coralogix firehose to Loggroups
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures:
        Ref: FunctionArchitecture
      MemorySize:
        Ref: FunctionMemorySize
      Timeout:
        Ref: FunctionTimeout
      Environment:
        Variables:
          LOGS_FILTER:
            Ref: LogsFilter
          REGEX_PATTERN:
            Ref: RegexPattern
          DESTINATION_ARN: 
            Ref: DestinationArn
          DESTINATION_ROLE: 
            Ref: DestinationRole
      Policies:
        - Statement:
            - Sid: CWSubscriptionPolicy
              Effect: Allow
              Action:
                - logs:PutSubscriptionFilter
              Resource:
                - "arn:aws:logs:*:*:*"
            - Sid: CXPassRole
              Effect: Allow
              Action: 
                - iam:PassRole
              Resource: 
                - !Sub "arn:aws:iam::${AWS::AccountId}:role/*"      
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SNS
  LambdaFunctionNotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsNotificationEnabled
    Properties:
      Protocol: email
      Endpoint:
        Ref: NotificationEmail
      TopicArn:
        Ref: LambdaFunction.DestinationTopic
