AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda-Manager
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-Lambda-Manager
    Description: Lambda-Manager
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - logs
      - cloudtrail
      - s3
      - lambda
    HomePageUrl: https://coralogix.com
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/coralogix/coralogix-aws-serverless
Parameters:
  RegexPattern:
    Type: String
    Description: Loggroup name regex pattern
    Default: \/aws\/lambda\/.*
  PrivateKey:
    Type: String
    Description: The Coralogix private key which is used to validate your authenticity
    NoEcho: true
  CoralogixRegion:
    Type: String
    Description: The Coralogix location region, possible options are [Europe, Europe2, India, Singapore, US]
    AllowedValues:
      - Europe
      - Europe2
      - India
      - Singapore
      - US
    Default: Europe
  ApplicationName:
    Type: String
    Description: The name of your application
    MinLength: 1
    MaxLength: 64
  SubsystemName:
    Type: String
    Description: The subsystem name of your application
    MinLength: 1
    MaxLength: 64
  FunctionArchitecture:
    Type: String
    Description: Lambda function architecture, possible options are [x86_64, arm64]
    AllowedValues:
      - x86_64
      - arm64
    Default: x86_64
  FunctionMemorySize:
    Type: Number
    Description: Lambda function memory limit
    MinValue: 128
    MaxValue: 3008
    Default: 1024
  FunctionTimeout:
    Type: Number
    Description: Lambda function timeout limit
    MinValue: 30
    MaxValue: 900
    Default: 300
  NotificationEmail:
    Type: String
    Description: Failure notification email address
    MaxLength: 320
    Default: ''
Mappings:
  CoralogixRegionMap:
    Europe:
      LogUrl: https://firehose-ingress.coralogix.com/firehose
    Europe2:
      LogUrl: https://firehose-ingress.eu2.coralogix.com/firehose
    India:
      LogUrl: https://firehose-ingress.coralogix.in/firehose
    Singapore:
      LogUrl: https://firehose-ingress.coralogixsg.com/firehose
    US:
      LogUrl: https://firehose-ingress.coralogix.us/firehose
Conditions:
  IsNotificationEnabled:
    Fn::Not:
      - Fn::Equals:
          - Ref: NotificationEmail
          - ''
Resources:
  CoralogixFirehoseFailed:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - '-'
        - - coralogixfirehosefailed
          - !Ref 'AWS::Region'
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  FirehoseLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'FirehoseAssumeRole'
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref "AWS::AccountId"

  AttachBucketPolicyToFirehoseLogsRole:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "S3BucketPermissionPolicy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
            Resource: 
              - "*"
      Roles:
        - Ref: FirehoseLogsRole
  CoralogixDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Join
        - '-'
        - - coralogixdeliverystream
          - !Ref 'AWS::Region'
      DeliveryStreamType: DirectPut
      HttpEndpointDestinationConfiguration:
        EndpointConfiguration:
          Name: "Coralogix"
          AccessKey:
            Ref: PrivateKey
          Url: !FindInMap
               - CoralogixRegionMap
               - Ref: CoralogixRegion
               - LogUrl
        RequestConfiguration:
          ContentEncoding: GZIP
          CommonAttributes:
            - AttributeName: "applicationName"
              AttributeValue: 
                Ref: ApplicationName
            - AttributeName: "subsystemName"
              AttributeValue: 
                Ref: SubsystemName
            - AttributeName: "integrationType"
              AttributeValue: "CloudWatch_JSON"
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 6
        RetryOptions:
          DurationInSeconds: 60
        S3BackupMode: FailedDataOnly
        S3Configuration:
          BucketARN: !GetAtt 
            - CoralogixFirehoseFailed
            - Arn
          CompressionFormat: UNCOMPRESSED
          RoleARN: !GetAtt FirehoseLogsRole.Arn
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref CoralogixFirehoseFailed
          LogStreamName: !Ref CoralogixFirehoseFailed
        ProcessingConfiguration:
          Enabled: false
        RoleARN: !GetAtt FirehoseLogsRole.Arn
        
  CloudwatchToFirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'CloudwatchToFirehoseRole'
            Effect: Allow
            Principal:
              Service: !Join
                - ''
                - - 'logs.'
                  - !Ref 'AWS::Region'
                  - '.amazonaws.com'
            Action: sts:AssumeRole
  CloudwatchToFirehoseAttachePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "CloudWatchFirehosePermissionPolicy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - firehose:PutRecord
              - firehose:PutRecordBatch
              - firehose:UpdateDestination
            Resource: !GetAtt CoralogixDeliveryStream.Arn
      Roles:
        - Ref: CloudwatchToFirehoseRole
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Adds Coralogix firehose to Loggroups
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Architectures:
        - Ref: FunctionArchitecture
      MemorySize:
        Ref: FunctionMemorySize
      Timeout:
        Ref: FunctionTimeout
      Environment:
        Variables:
          REGEX_PATTERN:
            Ref: RegexPattern
          FIREHOSE_ARN: !GetAtt 
            - CoralogixDeliveryStream
            - Arn
          FIREHOSE_ROLE: !GetAtt 
            - CloudwatchToFirehoseRole
            - Arn
          CORALOGIX_URL:
            Fn::FindInMap:
              - CoralogixRegionMap
              - Ref: CoralogixRegion
              - LogUrl
          private_key:
            Ref: PrivateKey
          app_name:
            Ref: ApplicationName
          sub_name:
            Ref: SubsystemName
      Policies:
        - Statement:
            - Sid: CWSubscriptionPolicy
              Effect: Allow
              Action:
                - logs:PutSubscriptionFilter
              Resource:
                - "arn:aws:logs:*:*:*"
            - Sid: CXPassRole
              Effect: Allow
              Action: 
                - iam:PassRole
              Resource: 
                - !Sub "arn:aws:iam::${AWS::AccountId}:role/*"      
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SNS
      Events:
        EventBridgeRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source: 
                - "aws.logs"
              detail-type:
                - "AWS API Call via CloudTrail"
              detail:
                eventSource:
                  - "logs.amazonaws.com"
                eventName:
                  - "CreateLogGroup"
            Target:
                Id: cx-loggroup-target
  LambdaFunctionNotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsNotificationEnabled
    Properties:
      Protocol: email
      Endpoint:
        Ref: NotificationEmail
      TopicArn:
        Ref: LambdaFunction.DestinationTopic