version = 0.1
[default.deploy.parameters]
stack_name = "sns-coudtrail"
resolve_s3 = true
s3_prefix = "sns-coudtrail"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CoralogixRegion=\"Europe\" ApplicationName=\"CT-New\" SubsystemName=\"CT-new\" SNSTopicArn=\"arn:aws:sns:us-east-1:771039649440:MySNS\" S3BucketName=\"aws-cloudtrail-logs-771039649440-e64d5f36\" S3KeyPrefix=\"AWSLogs/\" S3KeySuffix=\".json.gz\" FunctionArchitecture=\"x86_64\" FunctionMemorySize=\"1024\" FunctionTimeout=\"300\" NotificationEmail=\"\""
image_repositories = []
