AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function layer for using SSM for PrivateKey safe keeping .
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-Lambda-SSMLayer
    Description: Lambda function layer for using SSM for PrivateKey safe keeping.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - logs
      - lambda
      - extension
    HomePageUrl: https://coralogix.com
    SemanticVersion: 1.0.2
    SourceCodeUrl: https://github.com/coralogix/coralogix-aws-serverless
Parameters:
  CompatibleRuntimes:
    Type: CommaDelimitedList
    Description: Lambda Layer Version compatible runtimes
    Default: nodejs16.x, nodejs18.x, nodejs14.x
  RetentionPolicy:
    Type: String
    Description: Lambda Layer Version retention policy
    AllowedValues:
      - Retain
      - Delete
    Default: Retain
Resources:
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: coralogix-ssmlayer
      Description: Lambda function layer for using SSM for PrivateKey safe keeping
      LicenseInfo: Apache-2.0
      ContentUri: ./wrapper.zip
      CompatibleRuntimes:
        Ref: CompatibleRuntimes
      CompatibleArchitectures:
        - x86_64
        - arm64
      RetentionPolicy:
        Ref: RetentionPolicy
Outputs:
  LambdaLayerVersionArn:
    Description: Lambda Layer version ARN for coralogix-ssmlayer
    Value:
      Ref: LambdaLayer
    Export:
      Name: CORALOGIX-SSMLAYER
