AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Send data from Amazon MSK to Coralogix.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-MSK
    Description: Send data from Amazon MSK to Coralogix.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - logs
      - apache
      - kafka
      - msk
      - stream
    HomePageUrl: https://coralogix.com
    SemanticVersion: 1.0.13
    SourceCodeUrl: https://github.com/coralogix/coralogix-aws-serverless
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Coralogix configuration
        Parameters:
          - CoralogixRegion
          - CustomDomain
          - ApiKey
          - ApplicationName
          - SubsystemName
      - Label:
          default: Integration configuration
        Parameters:
          - MSKClusterArn
          - Topic
          - NotificationEmail
      - Label:
          default: Lambda configuration
        Parameters:
          - FunctionArchitecture
          - FunctionMemorySize
          - FunctionTimeout
      - Label:
          default: Security configuration
        Parameters:
          - LayerARN
Parameters:
  CoralogixRegion:
    Type: String
    Description: The Coralogix location region, possible options are [Europe, Europe2, India, Singapore, US, US2]
    AllowedValues:
      - Europe
      - Europe2
      - India
      - Singapore
      - US
      - US2
    Default: Europe
  CustomDomain:
    Type: String
    Description: The Coralogix custom domain
    Default: ''
  ApiKey:
    Type: String
    Description: The Coralogix Api key which is used to validate your authenticity
    NoEcho: true
  LayerARN:
    Type: String
    Description: In case you are using Secret Manager This is the ARN of the Coralogix Security lambda Layer.
    Default: ''
  ApplicationName:
    Type: String
    Description: The name of your application
    MinLength: 1
    MaxLength: 64
  SubsystemName:
    Type: String
    Description: The subsystem name of your application
    MaxLength: 64
    Default: ''
  MSKClusterArn:
    Type: String
    Description: The ARN of the Amazon MSK Kafka cluster
    MinLength: 20
    MaxLength: 2048
  Topic:
    Type: String
    Description: The name of the Kafka topic used to store records in your Kafka cluster
    AllowedPattern: '^[^.]([a-zA-Z0-9\.\-_]+)'
    ConstraintDescription: Allowed characters a-z, A-Z, 0-9, . (dot), _ (underscore), and - (dash)
    MinLength: 2
    MaxLength: 249
  FunctionArchitecture:
    Type: String
    Description: Lambda function architecture, possible options are [x86_64, arm64]
    AllowedValues:
      - x86_64
      - arm64
    Default: x86_64
  FunctionMemorySize:
    Type: Number
    Description: Lambda function memory limit
    MinValue: 128
    MaxValue: 3008
    Default: 1024
  FunctionTimeout:
    Type: Number
    Description: Lambda function timeout limit
    MinValue: 30
    MaxValue: 900
    Default: 300
  NotificationEmail:
    Type: String
    Description: Failure notification email address
    MaxLength: 320
    Default: ''
Mappings:
  CoralogixRegionMap:
    Europe:
      LogUrl: coralogix.com
    Europe2:
      LogUrl: eu2.coralogix.com
    India:
      LogUrl: coralogix.in
    Singapore:
      LogUrl: coralogixsg.com
    US:
      LogUrl: coralogix.us
    US2:
      LogUrl: cx498.coralogix.com
Conditions:
  IsNotificationEnabled:
    Fn::Not:
      - Fn::Equals:
          - Ref: NotificationEmail
          - ''
  IsSMEnabled:
    Fn::Not:
      - Fn::Equals:
          - Ref: LayerARN
          - ""
  IsNotSMEnabled:
    Fn::Equals:
      - Ref: LayerARN
      - ''
  IsRegionCustomUrlEmpty: !Not [!Equals [!Ref CustomDomain, ""]]
Resources:
  LambdaFunction:
    Condition: IsNotSMEnabled
    Type: AWS::Serverless::Function
    Properties:
      Description: Send data from Amazon MSK to Coralogix.
      CodeUri: ../kafka
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - Ref: FunctionArchitecture
      MemorySize:
        Ref: FunctionMemorySize
      Timeout:
        Ref: FunctionTimeout
      Environment:
        Variables:
          CORALOGIX_URL: !If
            - IsRegionCustomUrlEmpty
            - !Sub 'ingress.${CustomDomain}'
            - !Sub
              - '${Prefix}${Domain}'
              - Prefix: ingress.
                Domain: !FindInMap [CoralogixRegionMap, !Ref CoralogixRegion, LogUrl]
          private_key:
            Ref: ApiKey
          app_name:
            Ref: ApplicationName
          sub_name:
            Ref: SubsystemName
      Policies:
        - AWSLambdaMSKExecutionRole
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SNS
      Events:
        MSKEvent:
          Type: MSK
          Properties:
            Stream:
              Ref: MSKClusterArn
            StartingPosition: LATEST
            Topics:
              - Ref: Topic

  LambdaFunctionSM:
    Condition: IsSMEnabled
    Type: AWS::Serverless::Function
    Properties:
      Description: Send data from Amazon MSK to Coralogix.
      CodeUri: ../kafka
      Handler: index.handler
      Layers:
        - Ref: LayerARN
      Runtime: nodejs16.x
      Architectures:
        - Ref: FunctionArchitecture
      MemorySize:
        Ref: FunctionMemorySize
      Timeout:
        Ref: FunctionTimeout
      Environment:
        Variables:
          CORALOGIX_URL: !If
            - IsRegionCustomUrlEmpty
            - !Sub 'ingress.${CustomDomain}'
            - !Sub
              - '${Prefix}${Domain}'
              - Prefix: ingress.
                Domain: !FindInMap [CoralogixRegionMap, !Ref CoralogixRegion, LogUrl]
          AWS_LAMBDA_EXEC_WRAPPER: /opt/wrapper.sh         
          app_name:
            Ref: ApplicationName
          sub_name:
            Ref: SubsystemName
      Policies:
        - AWSLambdaMSKExecutionRole
        - SecretsManagerReadWrite
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SNS
          
      Events:
        MSKEvent:
          Type: MSK
          Properties:
            Stream:
              Ref: MSKClusterArn
            StartingPosition: LATEST
            Topics:
              - Ref: Topic

  PrivateKeySecret:
    Condition: IsSMEnabled
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: Coralogix Send Your Data key Secret
      Name: !Sub
        - 'lambda/coralogix/${AWS::Region}/${function}'
        - function: !Ref LambdaFunctionSM
      SecretString: !Ref ApiKey

  LambdaFunctionNotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsNotificationEnabled
    Properties:
      Protocol: email
      Endpoint:
        Ref: NotificationEmail
      TopicArn:
        !If
          - IsSMEnabled
          - !Ref LambdaFunctionSM.DestinationTopic
          - !Ref LambdaFunction.DestinationTopic