AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Send resource metadata to Coralogix.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-Resource-Metadata
    Description: Send resource metadata to Coralogix.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - metadata
    HomePageUrl: https://coralogix.com
    SemanticVersion: 1.0.1
    SourceCodeUrl: https://github.com/coralogix/coralogix-aws-serverless
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Coralogix Configuration
        Parameters:
          - CoralogixRegion
          - PrivateKey
      - Label:
          default: Metadata Collection Configuration
        Parameters:
          - Schedule
      - Label:
          default: AWS Lambda Metadata Collection Configuration
        Parameters:
          - LambdaApiRateLimit
          - LatestVersionsPerFunction
          - ResourceTtlMinutes
      - Label:
          default: Lambda Configuration
        Parameters:
          - FunctionArchitecture
          - FunctionMemorySize
          - FunctionTimeout
          - NotificationEmail
    ParameterLabels:
      CoralogixRegion:
        default: Region
      PrivateKey:
        default: Private Key
      Schedule:
        default: Schedule
      LambdaApiRateLimit:
        default: Lambda API Rate Limit
      LatestVersionsPerFunction:
        default: Latest Versions Per Function
      ResourceTtlMinutes:
        default: Resource Time-to-live (TTL) in Minutes
      FunctionArchitecture:
        default: Architecture
      FunctionMemorySize:
        default: Memory
      FunctionTimeout:
        default: Timeout
      NotificationEmail:
        default: Notification Email
Parameters:
  CoralogixRegion:
    Type: String
    Description: The Coralogix location region [Europe, Europe2, India, Singapore, US]
    AllowedValues:
      - DevShared
      - Staging
      - Europe
      - Europe2
      - India
      - Singapore
      - US
    Default: Europe
  PrivateKey:
    Type: String
    Description: The Coralogix private key which is used to validate your authenticity
    NoEcho: true
  Schedule:
    Type: String
    Description: Collect metadata on a specific schedule
    MaxLength: 256
    Default: "rate(10 minutes)"
  LambdaApiRateLimit:
    Description: Maximum number of calls (other than GetFunction) to Lambda API that the lambda will make
    MinValue: 1
    Default: 10
  LatestVersionsPerFunction:
    Description: How many latest published versions of each Lambda function should be collected
    MinValue: 0
    Default: 5
  ResourceTtlMinutes:
    Description: Once a resource is collected, how long should it remain valid?
    Default: 60
  FunctionArchitecture:
    Type: String
    Description: Lambda function architecture [x86_64, arm64]
    AllowedValues:
      - x86_64
      - arm64
    Default: x86_64
  FunctionMemorySize:
    Type: Number
    Description: Lambda function memory limit
    MinValue: 128
    MaxValue: 10240
    Default: 1024
  FunctionTimeout:
    Type: Number
    Description: Lambda function timeout limit
    MinValue: 30
    MaxValue: 900
    Default: 300
  NotificationEmail:
    Type: String
    Description: Failure notification email address
    MaxLength: 320
    Default: ""
Mappings:
  CoralogixRegionMap:
    DevShared:
      MetadataUrl: metadata-gateway.dev-shared.coralogix.net:443
    Staging:
      MetadataUrl: metadata-gateway.staging.coralogix.net:443
    Europe:
      MetadataUrl: metadata-gateway.coralogix.com:443
    Europe2:
      MetadataUrl: metadata-gateway.eu2.coralogix.com:443
    India:
      MetadataUrl: metadata-gateway.app.coralogix.in:443
    Singapore:
      MetadataUrl: metadata-gateway.coralogixsg.com:443
    US:
      MetadataUrl: metadata-gateway.coralogix.us:443
Conditions:
  IsNotificationEnabled:
    Fn::Not:
      - Fn::Equals:
          - Ref: NotificationEmail
          - ""
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Send resource metadata to Coralogix.
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - Ref: FunctionArchitecture
      MemorySize:
        Ref: FunctionMemorySize
      Timeout:
        Ref: FunctionTimeout
      Environment:
        Variables:
          CORALOGIX_METADATA_URL:
            Fn::FindInMap:
              - CoralogixRegionMap
              - Ref: CoralogixRegion
              - MetadataUrl
          PRIVATE_KEY:
            Ref: PrivateKey
          LAMBDA_API_RATE_LIMIT:
            Ref: LambdaApiRateLimit
          LATEST_VERSIONS_PER_FUNCTION:
            Ref: LatestVersionsPerFunction
          RESOURCE_TTL_MINUTES:
            Ref: ResourceTtlMinutes
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule:
              Ref: Schedule
            Enabled: True
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SNS
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Sid: GetResourcesPolicy
              Effect: Allow
              Action:
                - tag:GetResources
              Resource: "*"

  LambdaFunctionNotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsNotificationEnabled
    Properties:
      Protocol: email
      Endpoint:
        Ref: NotificationEmail
      TopicArn:
        Ref: LambdaFunction.DestinationTopic
