AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Send ECR image scans results to Coralogix.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-ECRImageFindings
    Description: Send ECR image scans results to Coralogix.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - logs
      - ecr
      - scan
      - image
      - vulnerabilities
    HomePageUrl: https://coralogix.com
    SemanticVersion: 1.0.2
    SourceCodeUrl: https://github.com/coralogix/coralogix-aws-serverless
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Coralogix configuration
        Parameters:
          - CoralogixRegion
          - CustomDomain
          - ApiKey
          - ApplicationName
          - SubsystemName
      - Label:
          default: Lambda configuration
        Parameters:
          - FunctionArchitecture
          - FunctionMemorySize
          - FunctionTimeout
    ParameterLabels:
      ApplicationName:
        default: Application Name
      SubsystemName:
        default: Subsystem Name
      ApiKey:
        default: Api Key
      CoralogixRegion:
        default: Coralogix Domain
      FunctionTimeout:
        default: Function Timeout
      FunctionMemorySize:
        default: Function Memory Size
      FunctionArchitecture:
        default: Function Architecture
Mappings:
  CoralogixDomainMap:
    Europe:
      LogUrl: https://ingress.coralogix.com/api/v1/logs
    Europe2:
      LogUrl: https://ingress.eu2.coralogix.com/api/v1/logs
    India:
      LogUrl: https://ingress.coralogix.in/api/v1/logs
    Singapore:
      LogUrl: https://ingress.coralogixsg.com/api/v1/logs
    US:
      LogUrl: https://ingress.coralogix.us/api/v1/logs
Parameters:
  ApiKey:
    Type: String
    Description: The Coralogix api key which is used to validate your authenticity
    NoEcho: true
  ApplicationName:
    Type: String
    Description: The name of your application
    MinLength: 1
    MaxLength: 64
  SubsystemName:
    Type: String
    Description: The subsystem name of your application
    MinLength: 1
    MaxLength: 64
  CoralogixRegion:
    Type: String
    Default: Europe
    Description: The domain that hosts the Coralogix account
    AllowedValues:
      - Europe
      - Europe2
      - India
      - Singapore
      - US
  FunctionArchitecture:
    Type: String
    Description: Lambda function architecture, possible options are [x86_64, arm64]
    AllowedValues:
      - x86_64
      - arm64
    Default: x86_64
  FunctionMemorySize:
    Type: Number
    Description: Lambda function memory limit
    MinValue: 128
    MaxValue: 3008
    Default: 1024
  FunctionTimeout:
    Type: Number
    Description: Lambda function timeout limit
    MinValue: 30
    MaxValue: 900
    Default: 300
  CustomDomain:
    Type: String
    Description: The Coralogix custom domain
    Default: ''
  NotificationEmail:
    Type: String
    Description: Failure notification email address
    MaxLength: 320
    Default: ''
Conditions:
  IsNotificationEnabled: !Not [!Equals [!Ref NotificationEmail, ""]]
  IsRegionCustomUrlNotEmpty: !Not [ !Equals [ !Ref CustomDomain, ""]]
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Sends ECR image scan findings to Coralogix
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - !Ref FunctionArchitecture
      MemorySize: !Ref FunctionMemorySize
      Timeout: !Ref FunctionTimeout
      Environment:
        Variables:
          app_name: !Ref ApplicationName
          sub_name: !Ref SubsystemName
          private_key: !Ref ApiKey
          CORALOGIX_LOG_URL: !If [IsRegionCustomUrlNotEmpty, !Sub "https://ingress.${CustomDomain}/api/v1/logs", !FindInMap [CoralogixDomainMap, !Ref CoralogixRegion, LogUrl]]
      Policies:
        - Statement:
          - Sid: EcrDescribeImageScanFindings
            Effect: Allow
            Action:
              - ecr:DescribeImageScanFindings
            Resource: "*"
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SNS
  LambdaFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !GetAtt EventBridgeRule.Arn
  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Join ['-', ['ECR-image-scan-lambda-invoke', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      State: ENABLED
      EventPattern:
        source:
          - aws.ecr
        detail-type:
          - ECR Image Scan
        detail:
          scan-status:
            - COMPLETE
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: !Ref LambdaFunction
  LambdaFunctionNotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsNotificationEnabled
    Properties:
      Protocol: email
      Endpoint: !Ref NotificationEmail
      TopicArn: !Ref LambdaFunction.DestinationTopic
