AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Import archived logs from S3 bucket to Coralogix.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-Archive-Reader
    Description: Import archived logs from S3 bucket to Coralogix.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - logs
      - s3
      - archive
      - import
      - restore
    HomePageUrl: https://coralogix.com
    SemanticVersion: 1.0.13
    SourceCodeUrl: https://github.com/coralogix/coralogix-aws-serverless
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Coralogix configuration
        Parameters:
          - CoralogixRegion
          - ApiKey
      - Label:
          default: Integration configuration
        Parameters:
          - NotificationEmail
      - Label:
          default: Lambda configuration
        Parameters:
          - FunctionArchitecture
          - FunctionMemorySize
          - FunctionTimeout
Parameters:
  CoralogixRegion:
    Type: String
    Description: The Coralogix location region, possible options are [Europe, Europe2, India, Singapore, US, US2]
    AllowedValues:
      - Europe
      - Europe2
      - India
      - Singapore
      - US
      - US2
    Default: Europe
  ApiKey:
    Type: String
    Description: The Coralogix Api key which is used to validate your authenticity
    NoEcho: true
  FunctionArchitecture:
    Type: String
    Description: Lambda function architecture, possible options are [x86_64, arm64]
    AllowedValues:
      - x86_64
      - arm64
    Default: x86_64
  FunctionMemorySize:
    Type: Number
    Description: Lambda function memory limit
    MinValue: 128
    MaxValue: 3008
    Default: 2048
  FunctionTimeout:
    Type: Number
    Description: Lambda function timeout limit
    MinValue: 30
    MaxValue: 900
    Default: 600
  NotificationEmail:
    Type: String
    Description: Failure notification email address
    MaxLength: 320
    Default: ''
Mappings:
  CoralogixRegionMap:
    Europe:
      LogUrl: https://ingress.coralogix.com/api/v1/logs
    Europe2:
      LogUrl: https://ingress.eu2.coralogix.com/api/v1/logs
    India:
      LogUrl: https://ingress.coralogix.in/api/v1/logs
    Singapore:
      LogUrl: https://ingress.coralogixsg.com/api/v1/logs
    US:
      LogUrl: https://ingress.coralogix.us/api/v1/logs
    US2:
      LogUrl: https://ingress.cx498.coralogix.com/api/v1/logs
Conditions:
  IsNotificationEnabled:
    Fn::Not:
      - Fn::Equals:
          - Ref: NotificationEmail
          - ''
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: coralogix-archive-reader
      Description: Import archived logs from S3 bucket to Coralogix.
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - Ref: FunctionArchitecture
      MemorySize:
        Ref: FunctionMemorySize
      Timeout:
        Ref: FunctionTimeout
      Environment:
        Variables:
          CORALOGIX_URL:
            Fn::FindInMap:
              - CoralogixRegionMap
              - Ref: CoralogixRegion
              - LogUrl
          private_key:
            Ref: ApiKey
      Policies:
        - S3ReadPolicy:
            BucketName:
              Fn::Sub: "coralogix-import-${AWS::AccountId}-${AWS::Region}"
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SNS
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket:
              Ref: LambdaBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .csv.gz

  LambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: "coralogix-import-${AWS::AccountId}-${AWS::Region}"

  LambdaFunctionNotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsNotificationEnabled
    Properties:
      Protocol: email
      Endpoint:
        Ref: NotificationEmail
      TopicArn:
        Ref: LambdaFunction.DestinationTopic

Outputs:
  LambdaBucketName:
    Description: Information about the value
    Value:
      Ref: LambdaBucket
    Export:
      Name: CORALOGIX-IMPORT-BUCKET
