AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Coralgoix Event-log SAM app - send salesforce event logs to Coraloigx
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-event-log
    Description: Get logs from Salesforce event-log and send them to Coralogix.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - logs
      - event-log
    HomePageUrl: https://coralogix.com
    SemanticVersion: 1.0.1
    SourceCodeUrl: "https://github.com/coralogix/coralogix-aws-serverless"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Coralogix Configuration
        Parameters:
          - CoralogixRegion
          - PrivateKey
          - ApplicationName
          - SubsystemName
      - Label:
          default: API Configuration
        Parameters:
          - SFSandbox
          - SFHost
          - SFEventType
          - SFClientId
          - SFClientSecret
          - SFUsername
          - SFPassword
      - Label:
          default: Lambda Configuration
        Parameters:
          - FunctionArchitecture
          - FunctionMemorySize
          - FunctionTimeout
          - FunctionSchedule
          - NotificationEmail
      - Label:
          default: Script Configuration
        Parameters:
          - LogsToStdout
    ParameterLabels:
      CoralogixRegion:
        default: Region
      PrivateKey:
        default: Private Key
      ApplicationName:
        default: Application Name
      SubsystemName:
        default: Subsystem Name
      SFSandbox:
        default: True or False if the this is a sandbox environment
      SFHost:
        default: The SF host only without .my.salesforce.com; <SF-HOST>.my.salesforce.com
      SFEventType:
        default: The wanted event to get logs for, leave empty for all events
      SFClientId:
        default: The application client id
      SFClientSecret:
        default: The application client secret
      SFUsername:
        default: The SF username
      SFPassword:
        default: The SF password
      FunctionArchitecture:
        default: Architecture
      FunctionMemorySize:
        default: Memory
      FunctionTimeout:
        default: Timeout
      FunctionSchedule:
        default: Scheduler
      NotificationEmail:
        default: Notification Email
      LogsToStdout:
        default: Logs to stdout
Parameters:
  CoralogixRegion:
    Type: String
    Description: The Coralogix location region [Europe, Europe2, India, Singapore, US]
    AllowedValues:
      - Europe
      - Europe2
      - India
      - Singapore
      - US
    Default: Europe
  PrivateKey:
    Type: String
    Description: The Coralogix private key which is used to validate your authenticity
    NoEcho: true
  ApplicationName:
    Type: String
    Description: The name of your application
    MinLength: 1
    MaxLength: 64
  SubsystemName:
    Type: String
    Description: The subsystem name of your application
    MinLength: 1
    MaxLength: 64
  SFSandbox:
    Type: String
    Description: True or False if this is a sandbox environment
    AllowedValues:
      - "True"
      - "False"
    Default: "False"
  SFHost:
    Type: String
    Description: The SF host only, without '.my.salesforce.com'; <SF-HOST>.my.salesforce.com
    NoEcho: true
  SFEventType:
    Type: String
    Description: The wanted event to get logs for, leave empty for all events
    Default: ""
  SFClientId:
    Type: String
    Description: The application client id
  SFClientSecret:
    Type: String
    Description: The application client secret
    NoEcho: true
  SFUsername:
    Type: String
    Description: The SF username
  SFPassword:
    Type: String
    Description: The SF password
    NoEcho: true
  FunctionArchitecture:
    Type: String
    Description: Lambda function architecture [x86_64, arm64]
    AllowedValues:
      - x86_64
      - arm64
    Default: x86_64
  FunctionMemorySize:
    Type: Number
    Description: Lambda function memory limit
    MinValue: 128
    MaxValue: 10240
    Default: 1024
  FunctionTimeout:
    Type: Number
    Description: Lambda function timeout limit
    MinValue: 60
    MaxValue: 900
    Default: 300
  FunctionSchedule:
    Type: Number
    Description: Lambda function schedule in hours
    MinValue: 2
    MaxValue: 72
    Default: 24
  NotificationEmail:
    Type: String
    Description: Failure notification email address
    MaxLength: 320
    Default: ""
  LogsToStdout:
    Type: String
    Description: Send logs to stdout/cloudwatch [True,False]
    AllowedValues:
      - "True"
      - "False"
    Default: "False"
Mappings:
  CoralogixRegionMap:
    Europe:
      LogUrl: https://ingress.coralogix.com/api/v1/logs
    Europe2:
      LogUrl: https://ingress.eu2.coralogix.com/api/v1/logs
    India:
      LogUrl: https://ingress.coralogix.in/api/v1/logs
    Singapore:
      LogUrl: https://ingress.coralogixsg.com/api/v1/logs
    US:
      LogUrl: https://ingress.coralogix.us/api/v1/logs
Conditions:
  ShouldCreateResource: !Not 
    - !Equals
      - !Ref NotificationEmail
      - ''
Resources:
  DynamoDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: 
        Name: id
        Type: String
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Send logs from Salesforce event-logs API to Coralogix.
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - Ref: FunctionArchitecture
      MemorySize:
        Ref: FunctionMemorySize
      Timeout:
        Ref: FunctionTimeout
      Environment:
        Variables:
          CORALOGIX_LOG_URL:
            Fn::FindInMap:
              - CoralogixRegionMap
              - Ref: CoralogixRegion
              - LogUrl
          CORALOGIX_PRIVATE_KEY:
            Ref: PrivateKey
          CORALOGIX_APPLICATION_NAME:
            Ref: ApplicationName
          CORALOGIX_SUBSYSTEM_NAME:
            Ref: SubsystemName
          DYNAMODB_TABLE:
            Ref: DynamoDB
          SF_SANDBOX_ENV:
            Ref: SFSandbox
          SF_HOST:
            Ref: SFHost
          SF_EVENT_TYPE:
            Ref: SFEventType
          SF_CLIENT_ID:
            Ref: SFClientId
          SF_CLIENT_SECRET:
            Ref: SFClientSecret
          SF_USERNAME:
            Ref: SFUsername
          SF_PASSWORD:
            Ref: SFPassword
          LOGS_TO_STDOUT:
            Ref: LogsToStdout
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SNS
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: DynamoDB
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule:
              Fn::Sub:
                - 'rate(${FunctionSchedule} hours)'
                - FunctionSchedule: !Ref FunctionSchedule
            Description: The Lambda schedule in hours.
            Enabled: true
  LambdaFunctionNotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: ShouldCreateResource
    Properties:
      Protocol: email
      Endpoint:
        Ref: NotificationEmail
      TopicArn:
        Ref: LambdaFunction.DestinationTopic