AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Collect and send cluster logs, metrics, events, alerts from MongoDB Atlas to Coralogix.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-MongoDB-Atlas
    Description: Collect and send cluster logs, metrics, events, alerts from MongoDB Atlas to Coralogix.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - mongodb
      - atlas
      - logs
      - metrics
      - events
      - alerts
    HomePageUrl: https://coralogix.com
    SemanticVersion: 1.0.11
    SourceCodeUrl: https://github.com/coralogix/coralogix-aws-serverless
Parameters:
  CoralogixRegion:
    Type: String
    Description: The Coralogix location region, possible options are [Europe, Europe2, India, Singapore, US]
    AllowedValues:
      - Europe
      - Europe2
      - India
      - Singapore
      - US
    Default: Europe
  PrivateKey:
    Type: String
    Description: The Coralogix private key which is used to validate your authenticity
    NoEcho: true
  ApplicationName:
    Type: String
    Description: The name of your application
    MaxLength: 64
  SubsystemName:
    Type: String
    Description: The subsystem name of your application
    MaxLength: 64
  FunctionArchitecture:
    Type: String
    Description: Lambda function architecture (x86_64, arm64)
    AllowedValues:
      - x86_64
      - arm64
    Default: x86_64
  FunctionMemorySize:
    Type: Number
    Description: Lambda function memory limit
    MinValue: 128
    MaxValue: 3008
    Default: 1024
  FunctionTimeout:
    Type: Number
    Description: Lambda function timeout limit
    MinValue: 30
    MaxValue: 900
    Default: 300
  Schedule:
    Type: String
    Description: MongoDB Atlas API pulling schedule
    MinLength: 3
    MaxLength: 320
    Default: 'rate(5 minutes)'
  Enabled:
    Type: String
    Description: MongoDB Atlas API pulling state
    AllowedValues:
      - True
      - False
    Default: True
  NotificationEmail:
    Type: String
    Description: Failure notification email address
    MaxLength: 320
    Default: ''
  MongoDBAtlasPublicKey:
    Type: String
    Description: MongoDB Atlas API Public Key
    MinLength: 1
    MaxLength: 255
  MongoDBAtlasPrivateKey:
    Type: String
    Description: MongoDB Atlas API Private Key
    MinLength: 1
    MaxLength: 255
    NoEcho: true
  MongoDBAtlasProjectName:
    Type: String
    Description: MongoDB Atlas Project Name
    MinLength: 1
  MongoDBAtlasResources:
    Type: String
    Description: MongoDB Atlas Resources to collect
    MinLength: 6
    Default: mongodb,mongodb-audit-log,mongos,mongos-audit-log,metrics,events,alerts
  MongoDBAtlasClusterName:
    Type: String
    Description: MongoDB Atlas Cluster Name
  MongoDBAtlasMetricsGranularity:
    Type: String
    Description: MongoDB Atlas Cluster Metrics granularity
    AllowedValues:
      - PT1M
      - PT5M
      - PT1H
      - P1D
    Default: PT5M
Mappings:
  CoralogixRegionMap:
    Europe:
      LogUrl: https://ingress.coralogix.com/api/v1/logs
    Europe2:
      LogUrl: https://ingress.eu2.coralogix.com/api/v1/logs
    India:
      LogUrl: https://ingress.coralogix.in/api/v1/logs
    Singapore:
      LogUrl: https://ingress.coralogixsg.com/api/v1/logs
    US:
      LogUrl: https://ingress.coralogix.us/api/v1/logs
Conditions:
  IsNotificationEnabled:
    Fn::Not:
      - Fn::Equals:
          - Ref: NotificationEmail
          - ''
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Collect and send cluster logs, metrics, events, alerts from MongoDB Atlas to Coralogix.
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - Ref: FunctionArchitecture
      MemorySize:
        Ref: FunctionMemorySize
      Timeout:
        Ref: FunctionTimeout
      Environment:
        Variables:
          CORALOGIX_URL:
            Fn::FindInMap:
              - CoralogixRegionMap
              - Ref: CoralogixRegion
              - LogUrl
          CORALOGIX_PRIVATE_KEY:
            Ref: PrivateKey
          CORALOGIX_APP_NAME:
            Ref: ApplicationName
          CORALOGIX_SUB_SYSTEM:
            Ref: SubsystemName
          MONGODB_ATLAS_PUBLIC_API_KEY:
            Ref: MongoDBAtlasPublicKey
          MONGODB_ATLAS_PRIVATE_API_KEY:
            Ref: MongoDBAtlasPrivateKey
          MONGODB_ATLAS_PROJECT_NAME:
            Ref: MongoDBAtlasProjectName
          MONGODB_ATLAS_RESOURCES:
            Ref: MongoDBAtlasResources
          MONGODB_ATLAS_CLUSTER_NAME:
            Ref: MongoDBAtlasClusterName
          MONGODB_ATLAS_METRICS_GRANULARITY:
            Ref: MongoDBAtlasMetricsGranularity
      Policies:
        - Statement:
            - Sid: LambdaReadOnly
              Effect: Allow
              Action:
                - lambda:GetFunction
                - lambda:ListTags
                - lambda:TagResource
              Resource:
                Fn::Sub: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*"
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SNS
      Events:
        CloudWatchSchedule:
          Type: Schedule
          Properties:
            Schedule:
              Ref: Schedule
            Enabled:
              Ref: Enabled

  LambdaFunctionNotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsNotificationEnabled
    Properties:
      Protocol: email
      Endpoint:
        Ref: NotificationEmail
      TopicArn:
        Ref: LambdaFunction.DestinationTopic