AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Generate report from Coralogix OpenSearch API and send it by email.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-Reporter
    Description: Generate report from Coralogix OpenSearch API and send it by email.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - logs
      - opensearch
      - elasticsearch
      - report
      - ses
      - email
    HomePageUrl: https://coralogix.com
    SemanticVersion: 2.0.2
    SourceCodeUrl: https://github.com/coralogix/coralogix-aws-serverless
Parameters:
  CoralogixRegion:
    Type: String
    Description: The Coralogix location region, possible options are [Europe, Europe2, India, Singapore, US, US2]
    AllowedValues:
      - Europe
      - Europe2
      - India
      - Singapore
      - US
      - US2
    Default: Europe
  LogsQueryKey:
    Type: String
    Description: The Coralogix Logs Query Key found under Data Flow > API Keys > Logs Query Key.
    NoEcho: true
  FunctionArchitecture:
    Type: String
    Description: Lambda function architecture, possible options are [x86_64, arm64]
    AllowedValues:
      - x86_64
      - arm64
    Default: x86_64
  FunctionMemorySize:
    Type: Number
    Description: Lambda function memory limit
    MinValue: 128
    MaxValue: 3008
    Default: 2048
  FunctionTimeout:
    Type: Number
    Description: Lambda function timeout limit
    MinValue: 30
    MaxValue: 900
    Default: 600
  Schedule:
    Type: String
    Description: Report sending schedule
    MinLength: 3
    MaxLength: 320
    Default: 'cron(0 0 * * ? *)'
  ScheduleEnable:
    Type: String
    Description: Report sending state
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  Sender:
    Type: String
    Description: Report sender email
    AllowedPattern: '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
    ConstraintDescription: The Sender should be valid email string
    MinLength: 3
    MaxLength: 320
  Recipient:
    Type: String
    Description: Report recipient email
    MinLength: 3
    Default: success@simulator.amazonses.com
  Subject:
    Type: String
    Description: Report email subject
    MinLength: 1
    MaxLength: 78
    Default: Coralogix Report
  Query:
    Type: String
    Description: OpenSearch query
    MinLength: 1
  Template:
    Type: String
    Description: Report template in JMESPath format
    MinLength: 1
  RequestTimeout:
    Type: Number
    Description: OpenSearch request timeout
    MinValue: 10000
    Default: 30000
  NotificationEmail:
    Type: String
    Description: Failure notification email address
    MaxLength: 320
    Default: ''
Mappings:
  CoralogixRegionMap:
    EU1:
      LogUrl: https://api.coralogix.com/data/os-api
    EU2:
      LogUrl: https://api.eu2.coralogix.com/data/os-api
    AP1:
      LogUrl: https://api.app.coralogix.in/data/os-api
    AP2:
      LogUrl: https://api.coralogixsg.com/data/os-api
    US1:
      LogUrl: https://api.coralogix.us/data/os-api
    US2:
      LogUrl: https://api.cx498.coralogix.com/data/os-api
Conditions:
  IsNotificationEnabled: !Not [!Equals [!Ref NotificationEmail, '']]
  IsScheduleEnabled: !Not [!Equals [!Ref ScheduleEnable, 'false']] 
    
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Generate report from Coralogix OpenSearch API and send it by email.
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - Ref: FunctionArchitecture
      MemorySize:
        Ref: FunctionMemorySize
      Timeout:
        Ref: FunctionTimeout
      Environment:
        Variables:
          coralogix_endpoint:
            Fn::FindInMap:
              - CoralogixRegionMap
              - Ref: CoralogixRegion
              - LogUrl
          logs_query_key:
            Ref: LogsQueryKey
          query:
            Ref: Query
          template:
            Ref: Template
          sender:
            Ref: Sender
          recipient:
            Ref: Recipient
          subject:
            Ref: Subject
          request_timeout:
            Ref: RequestTimeout
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
        - SESCrudPolicy:
            IdentityName:
              Ref: Sender
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SNS
      Events:
        CloudWatchSchedule:
          Type: Schedule
          Properties:
            Schedule:
              Ref: Schedule
            Enabled:
              Ref: IScheduleEnabled

  LambdaFunctionNotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsNotificationEnabled
    Properties:
      Protocol: email
      Endpoint:
        Ref: NotificationEmail
      TopicArn:
        Ref: LambdaFunction.DestinationTopic