AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Send CloudWatch metrics to Coralogix.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-CloudWatch-Metrics
    Description: Send CloudWatch metrics to Coralogix.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - metrics
      - cloudwatch
    HomePageUrl: https://coralogix.com
    SemanticVersion: 1.0.6
    SourceCodeUrl: https://github.com/coralogix/coralogix-aws-serverless
Parameters:
  CoralogixRegion:
    Type: String
    Description: The Coralogix location region, possible options are [Europe, Europe2, India, Singapore, US]
    AllowedValues:
      - Europe
      - Europe2
      - India
      - Singapore
      - US
    Default: Europe
  PrivateKey:
    Type: String
    Description: The Coralogix private key which is used to validate your authenticity
    NoEcho: true
  ApplicationName:
    Type: String
    Description: The name of your application
    MinLength: 1
    MaxLength: 64
  Metrics:
    Type: String
    Description: The list of CloudWatch metrics in JSON format (minified)
    MinLength: 2
    MaxLength: 4096
  FunctionArchitecture:
    Type: String
    Description: Lambda function architecture, possible options are [x86_64, arm64]
    AllowedValues:
      - x86_64
      - arm64
    Default: x86_64
  FunctionMemorySize:
    Type: Number
    Description: Lambda function memory limit
    MinValue: 128
    MaxValue: 3008
    Default: 1024
  FunctionTimeout:
    Type: Number
    Description: Lambda function timeout limit
    MinValue: 30
    MaxValue: 900
    Default: 300
  NotificationEmail:
    Type: String
    Description: Failure notification email address
    MaxLength: 320
    Default: ''
Mappings:
  CoralogixRegionMap:
    Europe:
      LogUrl: ingress.coralogix.com
    Europe2:
      LogUrl: ingress.eu2.coralogix.com
    India:
      LogUrl: ingress.app.coralogix.in
    Singapore:
      LogUrl: ingress.coralogixsg.com
    US:
      LogUrl: ingress.coralogix.us
Conditions:
  IsNotificationEnabled:
    Fn::Not:
      - Fn::Equals:
          - Ref: NotificationEmail
          - ''
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Send CloudWatch metrics to Coralogix.
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - Ref: FunctionArchitecture
      MemorySize:
        Ref: FunctionMemorySize
      Timeout:
        Ref: FunctionTimeout
      Environment:
        Variables:
          CORALOGIX_URL:
            Fn::FindInMap:
              - CoralogixRegionMap
              - Ref: CoralogixRegion
              - LogUrl
          private_key:
            Ref: PrivateKey
          app_name:
            Ref: ApplicationName
          metrics:
            Ref: Metrics
      Policies:
        - CloudWatchReadOnlyAccess
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SNS
      Events:
        CloudWatchSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(2 minutes)'
            Enabled: true

  LambdaFunctionNotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsNotificationEnabled
    Properties:
      Protocol: email
      Endpoint:
        Ref: NotificationEmail
      TopicArn:
        Ref: LambdaFunction.DestinationTopic