AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Send CloudWatch logs to Coralogix.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-CloudWatch
    Description: Send CloudWatch logs to Coralogix.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - logs
      - cloudwatch
    HomePageUrl: https://coralogix.com
    SemanticVersion: 1.0.11
    SourceCodeUrl: https://github.com/coralogix/coralogix-aws-serverless
Parameters:
  CoralogixRegion:
    Type: String
    Description: The Coralogix location region, possible options are [Europe, Europe2, India, Singapore, US]
    AllowedValues:
      - Europe
      - Europe2
      - India
      - Singapore
      - US
    Default: Europe
  PrivateKey:
    Type: String
    Description: The Coralogix private key which is used to validate your authenticity
    AllowedPattern: '[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}'
    ConstraintDescription: The PrivateKey should be valid UUID string
    MinLength: 36
    MaxLength: 36
    NoEcho: true
  ApplicationName:
    Type: String
    Description: The name of your application
    MinLength: 1
    MaxLength: 64
  SubsystemName:
    Type: String
    Description: The subsystem name of your application, if left empty will be populated from LogGroup name
    MaxLength: 64
    Default: ''
  NewlinePattern:
    Type: String
    Description: The pattern for lines splitting
    Default: '(?:\r\n|\r|\n)'
  BufferCharset:
    Type: String
    Description: The charset to use for buffer decoding, possible options are [utf8, ascii]
    AllowedValues:
      - utf8
      - ascii
    Default: utf8
  SamplingRate:
    Type: Number
    Description: Send messages with specific rate
    MinValue: 1
    Default: 1
  CloudWatchLogGroupName:
    Type: String
    Description: The name of the CloudWatch log group to watch
    AllowedPattern: '[\.\-_/#A-Za-z0-9]+'
    MinLength: 1
    MaxLength: 512
  FunctionArchitecture:
    Type: String
    Description: Lambda function architecture, possible options are [x86_64, arm64]
    AllowedValues:
      - x86_64
      - arm64
    Default: x86_64
  FunctionMemorySize:
    Type: Number
    Description: Lambda function memory limit
    MinValue: 128
    MaxValue: 3008
    Default: 1024
  FunctionTimeout:
    Type: Number
    Description: Lambda function timeout limit
    MinValue: 30
    MaxValue: 900
    Default: 300
  NotificationEmail:
    Type: String
    Description: Failure notification email address
    MaxLength: 320
    Default: ''
Mappings:
  CoralogixRegionMap:
    Europe:
      LogUrl: api.coralogix.com
    Europe2:
      LogUrl: api.eu2.coralogix.com
    India:
      LogUrl: api.app.coralogix.in
    Singapore:
      LogUrl: api.coralogixsg.com
    US:
      LogUrl: api.coralogix.us
Conditions:
  IsNotificationEnabled:
    Fn::Not:
      - Fn::Equals:
          - Ref: NotificationEmail
          - ''
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Send CloudWatch logs to Coralogix.
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs12.x
      Architectures:
        - Ref: FunctionArchitecture
      MemorySize:
        Ref: FunctionMemorySize
      Timeout:
        Ref: FunctionTimeout
      Environment:
        Variables:
          CORALOGIX_URL:
            Fn::FindInMap:
              - CoralogixRegionMap
              - Ref: CoralogixRegion
              - LogUrl
          private_key:
            Ref: PrivateKey
          app_name:
            Ref: ApplicationName
          sub_name:
            Ref: SubsystemName
          newline_pattern:
            Ref: NewlinePattern
          buffer_charset:
            Ref: BufferCharset
          sampling:
            Ref: SamplingRate
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SNS
      Events:
        CloudWatchLogsEvent:
          Type: CloudWatchLogs
          Properties:
            LogGroupName:
              Ref: CloudWatchLogGroupName
            FilterPattern: ''

  LambdaFunctionNotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsNotificationEnabled
    Properties:
      Protocol: email
      Endpoint:
        Ref: NotificationEmail
      TopicArn:
        Ref: LambdaFunction.DestinationTopic