name: Release

on:
  push:
    branches-ignore: [master]
  pull_request:
    types: [closed]
    branches: [master]

env:
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  infrastructure:
    name: Infrastructure
    runs-on: aws-sam
    env:
      AWS_SERVERLESS_BUCKET: coralogix-serverless-repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init
        working-directory: infra/
        run: terragrunt init

      - name: Validate
        working-directory: infra/
        run: terragrunt validate

      - name: Apply
        working-directory: infra/
        run: |
          terragrunt apply \
            -var="s3_bucket_name_prefix=${{ secrets.AWS_SERVERLESS_BUCKET }}" \
            -auto-approve

  check:
    name: Check
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get-changed-packages.outputs.packages }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get Changed Packages
        id: get-changed-packages
        run: |
          export PACKAGES=$(git diff --name-only --diff-filter=d ${{ github.event.pull_request.base.sha || 'origin/master' }} ${{ github.sha }} src/ | xargs -n1 dirname | xargs -n1 basename | sort | uniq | jq -rcnR '[inputs]')
          echo "::set-output name=packages::$PACKAGES"

  validate:
    name: Validate
    runs-on: aws-sam
    needs: check
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.check.outputs.packages) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate
        working-directory: src/${{ matrix.package }}
        run: sam validate

  build:
    name: Build
    runs-on: aws-sam
    needs: [check, validate]
    strategy:
      matrix:
        package: ${{ fromJSON(needs.check.outputs.packages) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        working-directory: ./src/${{ matrix.package }}
        run: sam build --use-container

      - name: Package
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
        working-directory: ./src/${{ matrix.package }}
        run: |
          sam package \
            --s3-bucket ${{ secrets.AWS_SERVERLESS_BUCKET }} \
            --s3-prefix ${{ matrix.package }} \
            --output-template-file packaged.yaml

      - name: Store
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.package }}-packaged.yaml
          path: src/${{ matrix.package }}/packaged.yaml

  publish:
    name: Publish
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
    runs-on: aws-sam
    needs: [infrastructure, check, build]
    strategy:
      matrix:
        package: ${{ fromJSON(needs.check.outputs.packages) }}
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.package }}-packaged.yaml

      - name: Publish
        run: sam publish --template packaged.yaml

      - name: Store
        run: |
          aws s3 cp \
            $(yq -r '.Resources.LambdaFunction.Properties.CodeUri' packaged.yaml) \
            s3://${{ secrets.AWS_SERVERLESS_BUCKET }}-${{ env.AWS_DEFAULT_REGION }}/${{ matrix.package }}.zip
